language: node_js
sudo: false
node_js:
    - "5.0"
    - "5.11"
    - "6"

cache:
  directories:
    - node_modules

notifications:
  email: false

branches:
  only:
    - develop
    - master

before_script:
    - npm install 

script:
  - npm run test
  - npm run test:coverage
  - npm run send-cover-report
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - npm run build
  - npm i pushstate-server -g
